name: Publish NuGet Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed for git rev-list to work

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Set version
        id: version
        run: |
          major=8
          minor=$(git rev-list --count origin/main)
          patch=${GITHUB_RUN_NUMBER}
          echo "VERSION=$major.$minor.$patch" >> $GITHUB_ENV
          echo "Version = $major.$minor.$patch"

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}

      - name: Pack NuGet
        run: dotnet pack --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ env.VERSION }}

      - name: Push package
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
